import { TrackProps } from "~/@types";

export const mockedTrackList: Array<TrackProps> = [
  {
    id: "1",
    title: "Test Track",
    length: 180,
    bpm: 120,
    genres: ["Pop"],
    moods: ["Happy"],
    main_artists: ["Test Artist"],
    featured_artists: ["Test Artist 2"],
    audio: "http://test.com",
    cover_art: "http://test.com",
    waveform: "http://test.com",
    spotify: "http://test.com",
  },
  {
    id: "2",
    title: "Another Track",
    length: 180,
    bpm: 120,
    genres: ["Rock"],
    moods: ["Happy"],
    main_artists: ["Another Test Artist"],
    featured_artists: ["Another Test Artist 2"],
    audio: "http://test.com",
    cover_art: "http://test.com",
    waveform: "http://test.com",
    spotify: "http://test.com",
  },
  {
    id: "3",
    title: "This is a Track",
    length: 180,
    bpm: 120,
    genres: ["Hip hop"],
    moods: ["Happy"],
    main_artists: ["Yet Another Test Artist"],
    featured_artists: ["Yet Another Test Artist 2"],
    audio: "http://test.com",
    cover_art: "http://test.com",
    waveform: "http://test.com",
    spotify: "http://test.com",
  },
];
