# Generated by Django 4.1.5 on 2024-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fetch_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tracks', models.ManyToManyField(blank=True, null=True, related_name='track', to='api.track')),
            ],
        ),
    ]
